#pragma once

const int INTAKE_ROLLER_CAN_ID = 66+1;
const int INTAKE_ANGLE_CAN_ID = 68+1;
const int CORAL_LAUNCHER_INDEXER_RIGHT_CAN_ID = 40;
const int CORAL_LAUNCHER_INDEXER_LEFT_CAN_ID = 41;

const int ALGAE_REMOVER_ARM_CAN_ID = 51;
const int ALGAE_REMOVER_WHEEL_CAN_ID = 50;

const int CLIMBER_WINCH_CAN_ID = 30;
