#pragma once

const int INTAKE_ROLLER_CAN_ID = 66+1;
const int INTAKE_ANGLE_CAN_ID = 68+1;

const int LAUNCHER_FLYWHEEL_RIGHT_CAN_ID = 43;
const int LAUNCHER_FLYWHEEL_LEFT_CAN_ID = 42;
const int LAUNCHER_INDEXER_RIGHT_CAN_ID = 40;
const int LAUNCHER_INDEXER_LEFT_CAN_ID = 41;

const int SPINDEXER_A_CAN_ID = 0;
const int SPINDEXER_B_CAN_ID = 0;
